# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/can_test.bd
# Block Designs: The module: 'can_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_can_0_0/can_test_can_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_can_0_0 || ORIG_REF_NAME==can_test_can_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_proc_sys_reset_0_0/can_test_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_proc_sys_reset_0_0 || ORIG_REF_NAME==can_test_proc_sys_reset_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_input_register_can_0_0/can_test_input_register_can_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_input_register_can_0_0 || ORIG_REF_NAME==can_test_input_register_can_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_tx_pulse_generator_0_0/can_test_tx_pulse_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_tx_pulse_generator_0_0 || ORIG_REF_NAME==can_test_tx_pulse_generator_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_frequency_test_0_0/can_test_frequency_test_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_frequency_test_0_0 || ORIG_REF_NAME==can_test_frequency_test_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_clk_wiz_0_2/can_test_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_clk_wiz_0_2 || ORIG_REF_NAME==can_test_clk_wiz_0_2} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_can_1_0/can_test_can_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_can_1_0 || ORIG_REF_NAME==can_test_can_1_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_axi_bram_ctrl_0_0/can_test_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_axi_bram_ctrl_0_0 || ORIG_REF_NAME==can_test_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_axi_bram_ctrl_0_bram_0/can_test_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==can_test_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_input_register_can_1_0/can_test_input_register_can_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_input_register_can_1_0 || ORIG_REF_NAME==can_test_input_register_can_1_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_axi_mem_intercon_0/can_test_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_axi_mem_intercon_0 || ORIG_REF_NAME==can_test_axi_mem_intercon_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_Gateway_Logik_0_axi_periph_0/can_test_Gateway_Logik_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_Gateway_Logik_0_axi_periph_0 || ORIG_REF_NAME==can_test_Gateway_Logik_0_axi_periph_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_Gateway_Logik_0_axi_periph_1_0/can_test_Gateway_Logik_0_axi_periph_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_Gateway_Logik_0_axi_periph_1_0 || ORIG_REF_NAME==can_test_Gateway_Logik_0_axi_periph_1_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_Gateway_Logik_0_0/can_test_Gateway_Logik_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_Gateway_Logik_0_0 || ORIG_REF_NAME==can_test_Gateway_Logik_0_0} -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_can_0_0/can_test_can_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_can_0_0 || ORIG_REF_NAME==can_test_can_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_can_0_0/can_test_can_0_0_ooc.xdc

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_proc_sys_reset_0_0/can_test_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_proc_sys_reset_0_0 || ORIG_REF_NAME==can_test_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_proc_sys_reset_0_0/can_test_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_proc_sys_reset_0_0 || ORIG_REF_NAME==can_test_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_clk_wiz_0_2/can_test_clk_wiz_0_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_clk_wiz_0_2 || ORIG_REF_NAME==can_test_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_clk_wiz_0_2/can_test_clk_wiz_0_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_clk_wiz_0_2 || ORIG_REF_NAME==can_test_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_clk_wiz_0_2/can_test_clk_wiz_0_2_ooc.xdc

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_can_1_0/can_test_can_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_can_1_0 || ORIG_REF_NAME==can_test_can_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_can_1_0/can_test_can_1_0_ooc.xdc

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_axi_bram_ctrl_0_bram_0/can_test_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/can_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'can_test'. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/can_test.bd
# Block Designs: The module: 'can_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_can_0_0/can_test_can_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_can_0_0 || ORIG_REF_NAME==can_test_can_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_proc_sys_reset_0_0/can_test_proc_sys_reset_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_proc_sys_reset_0_0 || ORIG_REF_NAME==can_test_proc_sys_reset_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_input_register_can_0_0/can_test_input_register_can_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_input_register_can_0_0 || ORIG_REF_NAME==can_test_input_register_can_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_tx_pulse_generator_0_0/can_test_tx_pulse_generator_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_tx_pulse_generator_0_0 || ORIG_REF_NAME==can_test_tx_pulse_generator_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_frequency_test_0_0/can_test_frequency_test_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_frequency_test_0_0 || ORIG_REF_NAME==can_test_frequency_test_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_clk_wiz_0_2/can_test_clk_wiz_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_clk_wiz_0_2 || ORIG_REF_NAME==can_test_clk_wiz_0_2} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_can_1_0/can_test_can_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_can_1_0 || ORIG_REF_NAME==can_test_can_1_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_axi_bram_ctrl_0_0/can_test_axi_bram_ctrl_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_axi_bram_ctrl_0_0 || ORIG_REF_NAME==can_test_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_axi_bram_ctrl_0_bram_0/can_test_axi_bram_ctrl_0_bram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==can_test_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_input_register_can_1_0/can_test_input_register_can_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_input_register_can_1_0 || ORIG_REF_NAME==can_test_input_register_can_1_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_axi_mem_intercon_0/can_test_axi_mem_intercon_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_axi_mem_intercon_0 || ORIG_REF_NAME==can_test_axi_mem_intercon_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_Gateway_Logik_0_axi_periph_0/can_test_Gateway_Logik_0_axi_periph_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_Gateway_Logik_0_axi_periph_0 || ORIG_REF_NAME==can_test_Gateway_Logik_0_axi_periph_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_Gateway_Logik_0_axi_periph_1_0/can_test_Gateway_Logik_0_axi_periph_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_Gateway_Logik_0_axi_periph_1_0 || ORIG_REF_NAME==can_test_Gateway_Logik_0_axi_periph_1_0} -quiet] -quiet

# IP: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.srcs/sources_1/bd/can_test/ip/can_test_Gateway_Logik_0_0/can_test_Gateway_Logik_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==can_test_Gateway_Logik_0_0 || ORIG_REF_NAME==can_test_Gateway_Logik_0_0} -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_can_0_0/can_test_can_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_can_0_0 || ORIG_REF_NAME==can_test_can_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_can_0_0/can_test_can_0_0_ooc.xdc

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_proc_sys_reset_0_0/can_test_proc_sys_reset_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_proc_sys_reset_0_0 || ORIG_REF_NAME==can_test_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_proc_sys_reset_0_0/can_test_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_proc_sys_reset_0_0 || ORIG_REF_NAME==can_test_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_clk_wiz_0_2/can_test_clk_wiz_0_2_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_clk_wiz_0_2 || ORIG_REF_NAME==can_test_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_clk_wiz_0_2/can_test_clk_wiz_0_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_clk_wiz_0_2 || ORIG_REF_NAME==can_test_clk_wiz_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_clk_wiz_0_2/can_test_clk_wiz_0_2_ooc.xdc

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_can_1_0/can_test_can_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==can_test_can_1_0 || ORIG_REF_NAME==can_test_can_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_can_1_0/can_test_can_1_0_ooc.xdc

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/ip/can_test_axi_bram_ctrl_0_bram_0/can_test_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: /home/upkmy/CAN_2Ch_BRAM_GW_v2/CAN_2Ch_BRAM_GW_v2.gen/sources_1/bd/can_test/can_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'can_test'. Do not add the DONT_TOUCH constraint.
